### ISSUE TITLE
Update Superset guide for Cloud

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#133]
It doesn't work as written, and some of the version numbers are out of date, so this user guide needs a refresh.

**Comment by DanRoscigno** [comment]
The SQLALCHEMY URL for my service in staging is:
```
clickhouse+native://default:<password>@<hostname>:9440/<database>?secure=true
```
Where:
`<password>`, `<hostname>`, and `<database>` come from the Native tab of the connection details. 


example
```
clickhouse+native://default:XXXXXXXXXX@xxxxxxx.xxxxxxxx.xxxxx.clickhouse.com:9440/default?secure=true
```


When I run Superset I run it in a container.  Here is my Dockerfile:
```
FROM apache/superset
# Switching to root to install the required packages
USER root

# Example: installing the MySQL driver to connect to the metadata database
# if you prefer Postgres, you may want to use `psycopg2-binary` instead
#RUN pip install mysqlclient

# Find which driver you need based on the analytics database
# you want to connect to here:
# https://superset.apache.org/installation.html#database-dependencies
RUN pip install clickhouse-driver==0.2.0
RUN pip install clickhouse-sqlalchemy==0.1.6

# Switching back to using the `superset` user
USER superset

# Setup account
RUN superset fab create-admin \
               --username admin \
               --firstname Superset \
               --lastname Admin \
               --email admin@superset.com \
               --password scoobydoo

# Update the local DB
RUN superset db upgrade

# Load examples
RUN superset load_examples

# Setup roles
RUN superset init
```

and docker-compose.yml
```
version: '3'
services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8088"
    image: minimal-superset
    volumes:
      - supersetminimal:/app
volumes:
  supersetminimal:
```
