### ISSUE TITLE
Detect broken links to external resources.

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-docs#685]
Some docs contain links to external resources. These links might be stale or broken as the external resources evolve unpredictably. We need a way to detect broken links to fix them timely. 
A few options come to mind:
- use a linter to validate links on CI and update broken links accordingly.
- use a link management service to keep stable URLs. The services usually provide usage statistics and a notification system.

**Comment by DanRoscigno** [comment]
@mshustov 

Looking at [htmltest](https://github.com/wjdp/htmltest)

Config file `.htmltest.yml`
```yml
DirectoryPath: build
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: true
IgnoreAltMissing: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true
```

Initial test:
```bash
cd clickhouse-docs
yarn install
yarn build
mkdir build/docs
cd build
mv en js ru zh css images assets img opensearch.xml category docs
cd ..
htmltest |grep -v "hash does not exist"
```

Some output (these are not meant to be live links, I need to fix this page):
```
docs/en/engines/table-engines/integrations/s3/index.html
  Non-OK status: 404 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://62VCH2MD74-dsn.algolia.net
  Non-OK status: 400 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://www.googletagmanager.com
  Non-OK status: 404 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://clickhouse-public-datasets.s3.amazonaws.com/my-bucket/some_folder/some_file_1.csv'
  Non-OK status: 404 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://clickhouse-public-datasets.s3.amazonaws.com/my-bucket/some_folder/some_file_2.csv'
  Non-OK status: 404 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://clickhouse-public-datasets.s3.amazonaws.com/my-bucket/some_folder/some_file_3.csv'
  Non-OK status: 404 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://clickhouse-public-datasets.s3.amazonaws.com/my-bucket/another_folder/some_file_1.csv'
  Non-OK status: 404 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://clickhouse-public-datasets.s3.amazonaws.com/my-bucket/another_folder/some_file_2.csv'
  Non-OK status: 404 --- docs/en/engines/table-engines/integrations/s3/index.html --> https://clickhouse-public-datasets.s3.amazonaws.com/my-bucket/another_folder/some_file_3.csv'
```

**Comment by mshustov** [comment]
@DanRoscigno looks good. Could you let me know if you plan to add it soon? Do you need any help with this?

**Comment by DanRoscigno** [comment]
I need to test it checking external only and see how long it takes.  If it takes too long I may run this on a schedule and not on each PR. Probably today.

**Comment by DanRoscigno** [comment]
Example config to:
- test external only URLs
- limit to the `integrations` dir
- ignore all `localhost`,  our Algolia search endpoint, and google tag manager URLs

```yml
DirectoryPath: build/docs/en/integrations
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: true
CheckInternal: false
CheckInternalHash: false
IgnoreAltMissing: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true
CacheExpires: 1h
IgnoreURLs:
  - https://62VCH2MD74-dsn.algolia.net
  - https://www.googletagmanager.com
  - http://localhost*
```
