### ISSUE TITLE
Update intro pages

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#736]
Docusaurus 2.3 GA seems to need a small change in the way `_category_.yml` specifies intro pages for the categories.  Here are our _category_.yml files:
```
❯ find . -name _category_.yml | xargs grep doc
./cloud/_category_.yml:  type: doc
./get-started/sql-console/_category_.yml:  type: doc
./integrations/data-ingestion/data-formats/_category_.yml:  type: doc
./getting-started/example-datasets/_category_.yml:  type: doc
./sql-reference/_category_.yml:  type: doc
./sql-reference/aggregate-functions/_category_.yml:  type: doc
./sql-reference/functions/_category_.yml:  type: doc
./sql-reference/statements/_category_.yml:  type: doc
```

We have been putting the markdown files for the categories in directories that are not in the nav and then specifying them like so:
```yml
position: 5
label: 'Data Formats'
collapsible: true
collapsed: true
link:
  type: doc
  id: en/integrations/data-formats
```
The change is to move the existing file into the dir where it will be used, and change the name to `intro.md`, and then to refer to it as `id: intro`.  Renaming is not strictly needed, but it is supposed to be the default according to the Docusaurus docs, so it is what we will do.  This also gets us around the problem of having to specify the pagination_next id -- it just works.  This also means that the author of a set of docs can put the intro page right in the dir, and not need to find a place to stash the file.
```yml
position: 5
label: 'Data Formats'
collapsible: true
collapsed: true
link:
  type: doc
  id: intro
```

Note: Make sure to add a slug to the frontmatter of the intro.md file that matches the old URL, or add a redirect so that the old URL for the category works.

Note: If the intro page is specified in the sidebars.js file, then modifying the _category_.yml does not help, probably the entry in sidebars.js needs to be changed to autogenerated and then update _category_.yml.  I will work on that later.
